import Head from "next/head";
import Image from "next/image";
import { Roboto } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Banner from "@/components/Banner/Banner";
import { useAppSelector } from "@/app/hooks";
import { selectCount } from "@/features/counter/counterSlice";


export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("hey here is banner btn click");
  };
  const count = useAppSelector(selectCount);
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
      </main>
    </>
  );
}
